### ISSUE TITLE
Wrong colors when decoding RLE sprites

### ISSUE THREAD

**Issue by cjschneider2** [briansteffens/rm-lib#1]
In your sprite code [here](https://github.com/briansteffens/rm-lib/blob/master/src/Sprites.cs#L128),
Your colours will turn out wrong because the colours are encoded as r5g6b5 normalized values so you should probably use something like this for the pixel decode loop:

```
    for (int p = 0; p < pixels; p++)
    {
            var data = br.USHORT();
            var b = (byte)((input & 0x1F) / 31.0f * 255);
            var g = (byte)(((input >> 5) & 0x3F) / 63.0f * 255);
            var r = (byte)(((input >> 11) & 0x1F) / 31.0f * 255);
            bmp.SetPixel(x, y, Color.FromArgb(255, r, g, b));
            x++;
    }
```
...not that I learned this the hard way while programming my own RLE viewer and wondering why the colours were off or anything ...  :)

**Comment by briansteffens** [comment]
Interesting, I was wondering what format the colors were in, thanks for the info! I'll give it a try when I get some time.

**Comment by cjschneider2** [comment]
I've actually have been meaning to help you out some but haven't been able to put much time into learning C#. My own RLE viewer is written in Rust and GTK, but I'd be happy to try to make an MFC Equivalent in C# (Both of which are something I've been meaning to learn...).  Or did you had another GUI framework in mind?

It was actually your repo which pushed me into finishing my version so thanks for that :) If you have any questions feel free to ask.

**Comment by briansteffens** [comment]
Nice, Rust is pretty cool.

I don't have many specific goals with this code, just messing around and having fun at the moment. I do have an item editor using C#/WinForms that I made some time ago that uses this library, but haven't worked on it for awhile.

I've been looking at the map files the last few days and trying to document those. It's going pretty well except I haven't been able to figure out the objects like houses/trees.

**Comment by briansteffens** [comment]
I made the change and the sprites came out better. Thanks for the info!
