### ISSUE TITLE
Snd.lst

### ISSUE THREAD

**Issue by cjschneider2** [briansteffens/rm-lib#4]
Do you have a copy of this file that is over 6kb?

The actual problem with reading this file (of the versions I can find) is that out of the 344 entries only 77-ish are listed in the file.

In general the data is really weird and uses the version 1.2 format even though it advertizes itself as version 1.0.

NOTE: The only difference in the 1.2 format is a copy of the file_idx at the last position.

**Comment by briansteffens** [comment]
Interesting, is this unique to `snd.lst` or does this apply to all lst files you've seen?

**Comment by cjschneider2** [comment]
Only the Obj.lst and Snd.lst used the 1.2 format though the Obj.lst correctly identifies itself. All the other files read correctly as far as I can tell. I only have files from a 3.9 client though...
